#!/usr/bin/env bash

apt="apt-cyg"
arg1=""

$apt update
$apt install $arg1 bash-completion vim grep sed less man diffutils
$apt install $arg1 openssh git tmux curl
$apt install $arg1 gzip tar unzip zip
$apt install $arg1 dos2unix xmlstarlet
$apt install $arg1 poppler-utils ||
$apt install $arg1 poppler
$apt install $arg1 fdisk dash
$apt install $arg1 fdupes
$apt install $arg1 eyed3
