#!/usr/bin/env bash

rename() {
    new_name="$1"
    replase_pattern=(.com .COM .ru .net .org .cc .fm .lol .top .me .best kbps)
    for i in ${replase_pattern[*]}; do
        pattern="s/([^(]*$i)//"
        new_name=$(echo "$new_name" | sed -e $pattern )
    done
    new_name=$(echo "$new_name" | sed -e 's/\[*.net\]//' -e 's/muzonov_net//')
    new_name=$(echo "$new_name" | sed -e 's/_-_/\ -\ /g')
    new_name=$(echo "$new_name" | sed -e 's/_/\ /g')
    new_name=$(echo "$new_name" | sed -e 's/\([^\ ].\)-\([^\ ].\)/\1\ \2/g')
    new_name=$(echo "$new_name" | sed -e 's/^\ //' -e 's/\ \.mp3/\.mp3/')
    new_name=$(echo "$new_name" | sed -e 's/\b./\u&/g')
    new_name=$(echo "$new_name" | sed -e 's/\.Mp3/\.mp3/g')
    echo "$new_name"
}

case $1 in
    -r|--rename)
        while [ "$#" -ne "1" ] ; do
            if [[ "$2" == *.mp3 ]] ; then
                new_name=$(rename "$2")
                if [[ "$2" != "$new_name" ]] ; then
                    echo "OLD: $2"
                    echo "NEW: $new_name"
                    echo "Rename music?(y/N)"
                    read item
                    if [ "$item" == y ]; then
                            mv "$2" "$new_name"
                    fi
                fi
            fi
        shift
        done
        ;;
    -t|--tag-remove)
        while [ "$#" -ne "1" ] ; do
            if [[ "$2" == *.mp3 ]] ; then
                eyeD3 --remove-all "$2"
            fi
        shift
        done
        ;;
    -h|--help|*)
        echo "-t|--tag-remove"
        echo "-r|--rename"
        ;;
esac
