#!/usr/bin/env bash

[ -z $(command -v convert) ] && echo "Please, install imagemagick" && exit
[ -z $(command -v dwebp) ] && echo "Please, install webp" && exit

case $1 in
  -c|--convert)
    while [ "$#" -ne "1" ] ; do
      if [[ "$2" == *.webp ]] ; then
        new_name=$(echo "$2" | sed -e 's/.webp/.png/')
        convert "$2" "$new_name" && rm "$2"
      fi
      shift
    done
    ;;
  -m|--min)
    while [ "$#" -ne "1" ] ; do
      if [[ "$2" == *.jpg ]] ; then
        mogrify -resize 600x600! "$2"
      fi
      shift
    done
    ;;
  -h|--help|*)
    echo "-c|--convert"
    echo "-m|--min"
    ;;
esac
